name: KMM, iOS, and macOS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v2
    - name: Set up Xcode 15
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "15.0.1"
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build Assessment Model
      run: ./gradlew :assessmentmodel:assembleKotlinModelDebugXCFramework
    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme iosApp -destination "platform=iOS Simulator,OS=latest,name=iPhone 15" -skipMacroValidation | xcpretty
    - name: Run tests for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme iosApp -destination "platform=iOS Simulator,OS=latest,name=iPhone 15" -skipMacroValidation | xcpretty
    - name: Set up Swift toolchain 5.9
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.9.0"
    - name: Build for macOS
      run: swift build -v
    - name: Run tests for macOS
      run: swift test -v
